# Users 



###
POST http://192.168.0.104:5000/api/auth/signup
Content-Type: application/json

{
    "firstName": "Matthew Henry",
    "lastName":"John",
    "email":"henry@gmail.com",
    "password":"123456",
    "dob":"15/05/1999",
    "selfie":"myself",
    "docs":"mydocs",
    "tel":"672973390"
}

# Login has a problem

###
POST http://localhost:5000/api/auth/login
Content-Type:application/json

{
    "email":"henry@gmail.com",
    "password":"123456"
}


###

POST http://localhost:5000/api/auth/logout



# All users

####
GEt http://localhost:5000/api/users


#Get a single user

####
GEt http://localhost:5000/api/users/66a916d0f0649f368c5062fc




####
PATCH http://localhost:5000/api/users/668683c2d82f350ed0687e82
Content-Type: application/json

{
    "firstName":"Betrandcliff",
    "lastName":"Sakwe"
}
X-Http-Method-Override: 

####
DELETE  http://localhost:5000/api/users/66a917cbf0649f368c5062ff




# Get user chats

###


GET http://localhost:5000/api/users/chats/66a2137e6ffa7b10305f1554


# Get user groups

###

GET http://localhost:5000/api/users/groups/66910153811265ee050ba667 



##Groups





#All groups

###
GET http://localhost:5000/api/groups



#Find Group by name

###
Get http://localhost:5000/api/groups/Liah



# Find a member in a group

###
post http://localhost:5000/api/groups/member/669fb9712ec164b0e9b7ce67
Content-Type: application/json

{
    "id":"669fb9582ec164b0e9b7ce66"
}





#create  a group

###
POST http://localhost:5000/api/groups
Content-Type: application/json

{
    "groupName":"Mens",
    "groupLevy":"30000",
    "groupIcon":"icon.png",
    "groupMembers":["67356777"],
    "groupAdmins":["66b09c619ee9a71b8eddbf3c"]
}

#Get group admins

###
GET http://localhost:5000/api/groups/admins/66ab8010d5a9212d81250bfd




#Get group members

###
GET http://localhost:5000/api/groups/members/66ab8010d5a9212d81250bfd


#add  group admin

###
PATCH  http://localhost:5000/api/groups/admins/66a0ad2fe2008f1ad5726a3b
Content-Type: application/json

{
    "userId":"66a0acbde2008f1ad5726a3s"
}


#add  group member

###
PATCH  http://localhost:5000/api/groups/members/66acaf3efdba2665ee7a5bda
Content-Type: application/json

{
     "userId":"66acaf2efdba2665ee7a5bd9"
}



#add  group approval

###
PATCH  http://localhost:5000/api/groups/approval/66acaf3efdba2665ee7a5bda
Content-Type: application/json

{
     "userId":"66acaf2efdba2665ee7a5bd9"
}





# Get group approval


###
GEt  http://localhost:5000/api/groups/approval/66acaf3efdba2665ee7a5bda

# 66acaf2efdba2665ee7a5bd9
# 66a0acbde2008f1ad5726a3a
# 66a0aeb2e2008f1ad5726a3d

66acaf3efdba2665ee7a5bda


#Delete  group member

###
DELETE   http://localhost:5000/api/groups/members/66acaf3efdba2665ee7a5bda
Content-Type: application/json

{
    "userId":"66acaf2efdba2665ee7a5bd9"
}


#Delete group admin

###
DELETE   http://localhost:5000/api/groups/admins/66571e6684334628302ee27c
Content-Type: application/json

{
    "userId":"66acaf2efdba2665ee7a5bd9"
}



#Delete request to join group


###
DELETE   http://localhost:5000/api/groups/approval/66acaf3efdba2665ee7a5bda
Content-Type: application/json

{
    "userId":"66ace1e6b8a1bab4f25a9387"
}

#66ace1e6b8a1bab4f25a9387



##USER CHAT LIST



###
GEt http://localhost:5000/api/user-chats/66a2137e6ffa7b10305f1554



##Add New Chat

###

PATCH  http://localhost:5000/api/user-chats/chats/66a0acbde2008f1ad5726a3a
Content-Type: application/json

{
    "userId":"66a0aeb2e2008f1ad5726a3d"
}



##Add New Groups

###

PATCH  http://localhost:5000/api/user-chats/groups/6658575e6fb7ae68270596d0
Content-Type: application/json

{
    "groupId":"jamesqu09s809s"
}



##AMessages

###

POST  http://localhost:5000/api/messages/send/665858adec9c9c696f2cbd52
Content-Type: application/json

{
    "message":"Hello boy"
}


#Get messages

###
GET http://localhost:5000/api/messages/665858adec9c9c696f2cbd52




#Get messages

###
POST   http://localhost:5000/api/messages/init
Content-Type: application/json

{
    "uid":"669f76936a056a2dfbae170c",
    "groupId":"669f76bc6a056a2dfbae170d"
}



###
POST   http://localhost:5000/api/messages/

Content-Type: application/json

{
    "uid":"66a238f558037cbe8683188b",
    "receiverId":"66a214176ffa7b10305f1555"
}




###

gET   http://localhost:5000/api/user-chats/groups/66b9ff89b9bcffb8bbd10017
# Content-Type: application/json

# {
#     "groups":["66b9a894cf6deb11a60bc3a8",
#       "66b9ab9acf6deb11a60bc3aa"]
# }